const versesArray = [
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.", verseReference: "Galatians 5:22" },
    { verseText: "God is our refuge and strength, an ever-present help in trouble.", verseReference: "Psalm 46:1" },
    { verseText: "The Lord your God is with you, the Mighty Warrior who saves.", verseReference: "Zephaniah 3:17" },
    { verseText: "Trust in the Lord with all your heart and lean not on your own understanding.", verseReference: "Proverbs 3:5" },
    { verseText: "The steadfast love of the Lord never ceases; his mercies never come to an end.", verseReference: "Lamentations 3:22" },
    { verseText: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", verseReference: "Psalm 32:8" },
    { verseText: "Therefore do not worry about tomorrow, for tomorrow will worry about itself.", verseReference: "Matthew 6:34" },
    { verseText: "The Lord will fight for you; you need only to be still.", verseReference: "Exodus 14:14" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "For we walk by faith, not by sight.", verseReference: "2 Corinthians 5:7" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "Delight yourself in the Lord, and he will give you the desires of your heart.", verseReference: "Psalm 37:4" },
    { verseText: "The Lord is good, a refuge in times of trouble. He cares for those who trust in him.", verseReference: "Nahum 1:7" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "Jesus Christ is the same yesterday and today and forever.", verseReference: "Hebrews 13:8" },
    { verseText: "Blessed are the peacemakers, for they will be called children of God.", verseReference: "Matthew 5:9" },
    { verseText: "Let all that you do be done in love.", verseReference: "1 Corinthians 16:14" },
    { verseText: "You are the light of the world. A town built on a hill cannot be hidden.", verseReference: "Matthew 5:14" },
    { verseText: "In the beginning God created the heavens and the earth.", verseReference: "Genesis 1:1" },
    { verseText: "And God said, 'Let there be light,' and there was light.", verseReference: "Genesis 1:3" },
    { verseText: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness, and self-control.", verseReference: "Galatians 5:22-23" },
    { verseText: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", verseReference: "John 3:16" },
    { verseText: "The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you.", verseReference: "Numbers 6:24-25" },
    { verseText: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", verseReference: "Philippians 4:6" },
    { verseText: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "He heals the brokenhearted and binds up their wounds.", verseReference: "Psalm 147:3" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "Come to me, all you who are weary and burdened, and I will give you rest.", verseReference: "Matthew 11:28" },
    { verseText: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.", verseReference: "Isaiah 26:3" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.", verseReference: "Philippians 4:19" },
    { verseText: "What, then, shall we say in response to these things? If God is for us, who can be against us?", verseReference: "Romans 8:31" },
    { verseText: "The Lord will fight for you; you need only to be still.", verseReference: "Exodus 14:14" },
    { verseText: "You are my refuge and my shield; I have put my hope in your word.", verseReference: "Psalm 119:114" },
    { verseText: "For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.", verseReference: "Ephesians 2:10" },
    { verseText: "Do not let your hearts be troubled. You believe in God; believe also in me.", verseReference: "John 14:1" },
    { verseText: "For God has not given us a spirit of fear, but of power and of love and of a sound mind.", verseReference: "2 Timothy 1:7" },
    { verseText: "A cheerful heart is good medicine, but a crushed spirit dries up the bones.", verseReference: "Proverbs 17:22" },
    { verseText: "As for me and my household, we will serve the Lord.", verseReference: "Joshua 24:15" },
    { verseText: "The Lord your God is with you, the Mighty Warrior who saves.", verseReference: "Zephaniah 3:17" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "I will praise you, Lord, with all my heart; I will tell of all your wonderful deeds.", verseReference: "Psalm 9:1" },
    { verseText: "My God will supply every need of yours according to his riches in glory in Christ Jesus.", verseReference: "Philippians 4:19" },
    { verseText: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary; they will walk and not be faint.", verseReference: "Isaiah 40:31" },
    { verseText: "For we walk by faith, not by sight.", verseReference: "2 Corinthians 5:7" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "Do not be afraid; I will help you.", verseReference: "Isaiah 41:13" },
    { verseText: "In all your ways acknowledge him, and he will make your paths straight.", verseReference: "Proverbs 3:6" },
    { verseText: "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.", verseReference: "Isaiah 43:2" },
    { verseText: "He will cover you with his feathers, and under his wings, you will find refuge; his faithfulness will be your shield and rampart.", verseReference: "Psalm 91:4" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "If you believe, you will receive whatever you ask for in prayer.", verseReference: "Matthew 21:22" },
    { verseText: "He has made everything beautiful in its time.", verseReference: "Ecclesiastes 3:11" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "A friend loves at all times, and a brother is born for a time of adversity.", verseReference: "Proverbs 17:17" },
    { verseText: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", verseReference: "2 Corinthians 5:17" },
    { verseText: "God is our refuge and strength, an ever-present help in trouble.", verseReference: "Psalm 46:1" },
    { verseText: "I will bless the Lord at all times; his praise shall continually be in my mouth.", verseReference: "Psalm 34:1" },
    { verseText: "You make known to me the path of life; you will fill me with joy in your presence, with eternal pleasures at your right hand.", verseReference: "Psalm 16:11" },
    { verseText: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.", verseReference: "Revelation 21:4" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "But the one who endures to the end will be saved.", verseReference: "Matthew 24:13" },
    { verseText: "The Lord your God is with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.", verseReference: "Micah 6:8" },
    { verseText: "Now faith is confidence in what we hope for and assurance about what we do not see.", verseReference: "Hebrews 11:1" },
    { verseText: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", verseReference: "Galatians 6:9" },
    { verseText: "The peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", verseReference: "Philippians 4:7" },
    { verseText: "We love because he first loved us.", verseReference: "1 John 4:19" },
    { verseText: "Be strong and take heart, all you who hope in the Lord.", verseReference: "Psalm 31:24" },
    { verseText: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "Keep your lives free from the love of money and be content with what you have, because God has said, 'Never will I leave you; never will I forsake you.'", verseReference: "Hebrews 13:5" },
    { verseText: "I am the way, the truth, and the life. No one comes to the Father except through me.", verseReference: "John 14:6" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear?", verseReference: "Psalm 27:1" },
    { verseText: "For the Lord your God is a consuming fire, a jealous God.", verseReference: "Deuteronomy 4:24" },
    { verseText: "Your word is a lamp for my feet, a light on my path.", verseReference: "Psalm 119:105" },
    { verseText: "God is our refuge and strength, an ever-present help in trouble.", verseReference: "Psalm 46:1" },
    { verseText: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.", verseReference: "James 1:17" },
    { verseText: "He said to them, 'Go into all the world and preach the gospel to all creation.'", verseReference: "Mark 16:15" },
    { verseText: "When the righteous thrive, the people rejoice; when the wicked rule, the people groan.", verseReference: "Proverbs 29:2" },
    { verseText: "A man’s heart plans his way, but the Lord directs his steps.", verseReference: "Proverbs 16:9" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "Do not let your hearts be troubled and do not be afraid.", verseReference: "John 14:27" },
    { verseText: "The heart is deceitful above all things and beyond cure. Who can understand it?", verseReference: "Jeremiah 17:9" },
    { verseText: "You will know the truth, and the truth will set you free.", verseReference: "John 8:32" },
    { verseText: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness, and self-control.", verseReference: "Galatians 5:22-23" },
    { verseText: "If God is for us, who can be against us?", verseReference: "Romans 8:31" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love.", verseReference: "1 John 4:18" },
    { verseText: "What is impossible with man is possible with God.", verseReference: "Luke 18:27" },
    { verseText: "No weapon forged against you will prevail, and you will refute every tongue that accuses you.", verseReference: "Isaiah 54:17" },
    { verseText: "With man this is impossible, but with God all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "He will cover you with his feathers, and under his wings, you will find refuge.", verseReference: "Psalm 91:4" },
    { verseText: "If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you.", verseReference: "John 15:7" },
    { verseText: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.", verseReference: "Proverbs 3:5-6" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "It is for freedom that Christ has set us free; stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.", verseReference: "Galatians 5:1" },
    { verseText: "He will call on me, and I will answer him; I will be with him in trouble, I will deliver him and honor him.", verseReference: "Psalm 91:15" },
    { verseText: "So do not fear, for I am with you; do not be dismayed, for I am your God.", verseReference: "Isaiah 41:10" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "Let us fix our eyes on Jesus, the author and perfecter of our faith.", verseReference: "Hebrews 12:2" },
    { verseText: "You are my hiding place; you will protect me from trouble and surround me with songs of deliverance.", verseReference: "Psalm 32:7" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "The Lord will never leave you nor forsake you.", verseReference: "Deuteronomy 31:6" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "But those who hope in the Lord will renew their strength.", verseReference: "Isaiah 40:31" },
    { verseText: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.", verseReference: "Isaiah 26:3" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.", verseReference: "Zephaniah 3:17" },
    { verseText: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.", verseReference: "2 Timothy 1:7" },
    { verseText: "You are the light of the world. A city on a hill cannot be hidden.", verseReference: "Matthew 5:14" },
    { verseText: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", verseReference: "James 1:5" },
    { verseText: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.", verseReference: "Colossians 3:23" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "He brought me out into a spacious place; he rescued me because he delighted in me.", verseReference: "Psalm 18:19" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "Rejoice in the Lord always. I will say it again: Rejoice!", verseReference: "Philippians 4:4" },
    { verseText: "Let not your hearts be troubled. Believe in God; believe also in me.", verseReference: "John 14:1" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "The Lord is my shepherd, I shall not want.", verseReference: "Psalm 23:1" },
    { verseText: "Do not be afraid, for I have redeemed you; I have summoned you by name; you are mine.", verseReference: "Isaiah 43:1" },
    { verseText: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary; they will walk and not be faint.", verseReference: "Isaiah 40:31" },
    { verseText: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.", verseReference: "Galatians 5:22" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "We love because he first loved us.", verseReference: "1 John 4:19" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "Do not fear, for I have redeemed you; I have summoned you by name; you are mine.", verseReference: "Isaiah 43:1" },
    { verseText: "No weapon forged against you will prevail, and you will refute every tongue that accuses you.", verseReference: "Isaiah 54:17" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "For the Spirit God gave us does not make us timid, but gives us power, love, and self-discipline.", verseReference: "2 Timothy 1:7" },
    { verseText: "Let all that you do be done in love.", verseReference: "1 Corinthians 16:14" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "But the one who endures to the end will be saved.", verseReference: "Matthew 24:13" },
    { verseText: "If God is for us, who can be against us?", verseReference: "Romans 8:31" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.", verseReference: "Micah 6:8" },
    { verseText: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", verseReference: "Psalm 32:8" },
    { verseText: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.", verseReference: "Galatians 5:22" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "Do not be afraid; I will help you.", verseReference: "Isaiah 41:13" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "We love because he first loved us.", verseReference: "1 John 4:19" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "Trust in the Lord with all your heart and lean not on your own understanding.", verseReference: "Proverbs 3:5" },
    { verseText: "When the righteous thrive, the people rejoice; when the wicked rule, the people groan.", verseReference: "Proverbs 29:2" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "For we live by faith, not by sight.", verseReference: "2 Corinthians 5:7" },
    { verseText: "The Lord will never leave you nor forsake you.", verseReference: "Deuteronomy 31:6" },
    { verseText: "He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.", verseReference: "Micah 6:8" },
    { verseText: "I will praise you, Lord, with all my heart; I will tell of all your wonderful deeds.", verseReference: "Psalm 9:1" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "For the Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.", verseReference: "Zephaniah 3:17" },
    { verseText: "Do not be afraid, for I am with you; do not be dismayed, for I am your God.", verseReference: "Isaiah 41:10" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", verseReference: "Psalm 32:8" },
    { verseText: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", verseReference: "James 1:5" },
    { verseText: "So do not fear, for I am with you; do not be dismayed, for I am your God.", verseReference: "Isaiah 41:10" },
    { verseText: "Rejoice in the Lord always. I will say it again: Rejoice!", verseReference: "Philippians 4:4" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "The Lord your God is with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "Do not be afraid, for I have redeemed you; I have summoned you by name; you are mine.", verseReference: "Isaiah 43:1" },
    { verseText: "But the one who endures to the end will be saved.", verseReference: "Matthew 24:13" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "For the Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.", verseReference: "Zephaniah 3:17" },
    { verseText: "You are my hiding place; you will protect me from trouble and surround me with songs of deliverance.", verseReference: "Psalm 32:7" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "Do not be afraid; I will help you.", verseReference: "Isaiah 41:13" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "But the one who endures to the end will be saved.", verseReference: "Matthew 24:13" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "Rejoice in the Lord always. I will say it again: Rejoice!", verseReference: "Philippians 4:4" },
    { verseText: "For the Spirit God gave us does not make us timid, but gives us power, love, and self-discipline.", verseReference: "2 Timothy 1:7" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "But the one who endures to the end will be saved.", verseReference: "Matthew 24:13" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "I will praise you, Lord, with all my heart; I will tell of all your wonderful deeds.", verseReference: "Psalm 9:1" },
    { verseText: "For the Spirit God gave us does not make us timid, but gives us power, love, and self-discipline.", verseReference: "2 Timothy 1:7" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "Let not your hearts be troubled. Believe in God; believe also in me.", verseReference: "John 14:1" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "Rejoice in the Lord always. I will say it again: Rejoice!", verseReference: "Philippians 4:4" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "Do not be afraid; I will help you.", verseReference: "Isaiah 41:13" },
    { verseText: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", verseReference: "Psalm 32:8" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "For the Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.", verseReference: "Zephaniah 3:17" },
    { verseText: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "I will praise you, Lord, with all my heart; I will tell of all your wonderful deeds.", verseReference: "Psalm 9:1" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "For the Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.", verseReference: "Zephaniah 3:17" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "You are my hiding place; you will protect me from trouble and surround me with songs of deliverance.", verseReference: "Psalm 32:7" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "For the Spirit God gave us does not make us timid, but gives us power, love, and self-discipline.", verseReference: "2 Timothy 1:7" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "You are my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "Rejoice in the Lord always. I will say it again: Rejoice!", verseReference: "Philippians 4:4" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "Rejoice in the Lord always. I will say it again: Rejoice!", verseReference: "Philippians 4:4" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "Let us come before him with thanksgiving and extol him with music and song.", verseReference: "Psalm 95:2" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "I will fear no evil, for you are with me; your rod and your staff, they comfort me.", verseReference: "Psalm 23:4" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", verseReference: "Romans 8:28" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "Be still, and know that I am God; I will be exalted among the nations; I will be exalted in the earth.", verseReference: "Psalm 46:10" },
    { verseText: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", verseReference: "Psalm 28:7" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is righteous in all his ways and faithful in all he does.", verseReference: "Psalm 145:17" },
    { verseText: "The Lord is compassionate and gracious, slow to anger, abounding in love.", verseReference: "Psalm 103:8" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", verseReference: "Philippians 1:6" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame.", verseReference: "Isaiah 58:11" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "Even to your old age and gray hairs I am he, I am he who will sustain you.", verseReference: "Isaiah 46:4" },
    { verseText: "Cast all your anxiety on him because he cares for you.", verseReference: "1 Peter 5:7" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", verseReference: "Jeremiah 29:11" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "The Lord is near to the brokenhearted and saves the crushed in spirit.", verseReference: "Psalm 34:18" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "With God, all things are possible.", verseReference: "Matthew 19:26" },
    { verseText: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", verseReference: "Joshua 1:9" },
    { verseText: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", verseReference: "Proverbs 18:10" },
    { verseText: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?", verseReference: "Psalm 27:1" },
    { verseText: "I sought the Lord, and he answered me; he delivered me from all my fears.", verseReference: "Psalm 34:4" },
    { verseText: "He gives strength to the weary and increases the power of the weak.", verseReference: "Isaiah 40:29" },
    { verseText: "When I am afraid, I put my trust in you.", verseReference: "Psalm 56:3" },
    { verseText: "I can do all this through him who gives me strength.", verseReference: "Philippians 4:13" },
    { verseText: "The Lord is good to those whose hope is in him, to the one who seeks him.", verseReference: "Lamentations 3:25" },
    { verseText: "This is the day that the Lord has made; let us rejoice and be glad in it.", verseReference: "Psalm 118:24" },
    { verseText: "The Lord is my strength and my song; he has become my salvation.", verseReference: "Exodus 15:2" },
    { verseText: "The Lord is my rock and my fortress; for your name’s sake, lead me and guide me.", verseReference: "Psalm 31:3" },
    { verseText: "The Lord is my shepherd, I lack nothing.", verseReference: "Psalm 23:1" },
    { verseText: "The Lord will keep you from all harm; he will watch over your life.", verseReference: "Psalm 121:7" },
    { verseText: "Let everything that has breath praise the Lord.", verseReference: "Psalm 150:6" }

]